// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeHg32VjgFEPlnwQ1djM1krCQ3lz8GDUY',
    appId: '1:1037511136316:web:95de50d6e646b6edef1f39',
    messagingSenderId: '1037511136316',
    projectId: 'chamber-60982',
    authDomain: 'chamber-60982.firebaseapp.com',
    databaseURL: 'https://chamber-60982-default-rtdb.firebaseio.com',
    storageBucket: 'chamber-60982.appspot.com',
    measurementId: 'G-GPV34P0RYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPl-sWg1aBYbphP4rlY8f64n66Bx7maZc',
    appId: '1:1037511136316:android:ad07149f6f389c73ef1f39',
    messagingSenderId: '1037511136316',
    projectId: 'chamber-60982',
    databaseURL: 'https://chamber-60982-default-rtdb.firebaseio.com',
    storageBucket: 'chamber-60982.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-_OLsR3YXSMMKuUd5f015qVBaSFOfdbU',
    appId: '1:1037511136316:ios:b807b07a0932959def1f39',
    messagingSenderId: '1037511136316',
    projectId: 'chamber-60982',
    databaseURL: 'https://chamber-60982-default-rtdb.firebaseio.com',
    storageBucket: 'chamber-60982.appspot.com',
    iosBundleId: 'com.example.chamberOfCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-_OLsR3YXSMMKuUd5f015qVBaSFOfdbU',
    appId: '1:1037511136316:ios:b807b07a0932959def1f39',
    messagingSenderId: '1037511136316',
    projectId: 'chamber-60982',
    databaseURL: 'https://chamber-60982-default-rtdb.firebaseio.com',
    storageBucket: 'chamber-60982.appspot.com',
    iosBundleId: 'com.example.chamberOfCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeHg32VjgFEPlnwQ1djM1krCQ3lz8GDUY',
    appId: '1:1037511136316:web:ca70b89801724d7eef1f39',
    messagingSenderId: '1037511136316',
    projectId: 'chamber-60982',
    authDomain: 'chamber-60982.firebaseapp.com',
    databaseURL: 'https://chamber-60982-default-rtdb.firebaseio.com',
    storageBucket: 'chamber-60982.appspot.com',
    measurementId: 'G-WQS1PB0ZCY',
  );
}
